In [ ]:
import numpy as np
 # to get a random 4 * 4 matrix
matrix = np.random.randint(1, 100, size=(4, 4))
print("INITIAL  MATRIX:\n", matrix)

INITIAL  MATRIX:
 [[3 9 2 4]
 [1 1 8 3]
 [3 3 9 3]
 [9 6 7 2]]


In [ ]:
#to make its transpose
transpose = ([[0,0,0,0],
          [0,0,0,0],
          [0,0,0,0],
          [0,0,0,0]])

for i in range(len(matrix)):
   # iterate through columns
   for j in range(len(matrix[0])):
       transpose[j][i] = matrix[i][j]
print(transpose)

[[3, 1, 3, 9], [9, 1, 3, 6], [2, 8, 9, 7], [4, 3, 3, 2]]


In [ ]:
multiplied_matrix = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
for i in range(len(matrix)):
   for j in range(len(transpose[0])):
       for k in range(len(transpose)):
           multiplied_matrix[i][j] += matrix[i][k] * transpose[k][j]
print(multiplied_matrix)

[[110, 40, 66, 103], [40, 75, 87, 77], [66, 87, 108, 114], [103, 77, 114, 170]]


In [ ]:
Reshaped_Matrix = np.reshape(multiplied_matrix, (2, 8))

print("Reshaped Matrix : ")
print(Reshaped_Matrix)

Reshaped Matrix : 
[[110  40  66 103  40  75  87  77]
 [ 66  87 108 114 103  77 114 170]]
