In [1]:
import numpy as np

In [9]:
matrix = np.random.rand(4, 4)
print(matrix)

[[0.2289156  0.63309736 0.7360207  0.23774963]
 [0.80024592 0.10077604 0.68696136 0.18365737]
 [0.79558854 0.20341337 0.05415621 0.5581372 ]
 [0.58955239 0.60067897 0.47494336 0.913567  ]]


In [10]:
result = np.empty((4, 4))
for i in range(4):
    for j in range(4):
        result[i, j] = sum(matrix[i, k] * matrix[j, k] for k in range(4))
print(result)


[[1.05146598 0.79627208 0.4834601  1.08201437]
 [0.79627208 1.15619529 0.79687491 1.02637199]
 [0.4834601  0.79687491 0.98878816 1.12684412]
 [1.08201437 1.02637199 1.12684412 1.7685631 ]]


In [11]:
reshaped_result = np.reshape(result, (2, 8))
print(reshaped_result)

[[1.05146598 0.79627208 0.4834601  1.08201437 0.79627208 1.15619529
  0.79687491 1.02637199]
 [0.4834601  0.79687491 0.98878816 1.12684412 1.08201437 1.02637199
  1.12684412 1.7685631 ]]
